export type ActivationKey = "化禄" | "化权" | "化科" | "化忌";

export type PalaceKey = "命宫" | "兄弟" | "夫妻" | "子女" | "财帛" | "疾厄" | "迁移" | "交友" | "官禄" | "田宅" | "福德" | "父母";

export type ActivationEntry = {
  paragraphs: string[];
};

export const ACTIVATION_PALACE_MEANINGS: Record<
  ActivationKey,
  Partial<Record<PalaceKey, ActivationEntry>>
> = {
  化禄: {
    命宫: {
      paragraphs: [
        "In your Life Palace, Lu, the nourishing tide, rises behind your ribs. It softens your stance and coats your voice with a gentle sheen. People feel safer around you, and you feel more willing to receive. The inner weather turns warm and buttery, like a fresh loaf breathing on the table, steam curling into the room. Appetite grows: for connection, for learning, for nice textures against your skin. This is not greed so much as permission; you allow yourself to want. Your charisma comes from ease, not push. You magnetize helpers and opportunities when you relax your jaw and stay curious. Yet this abundance can lull. If you drift, comfort becomes a padded room. The archetype here is the hospitable host: you set a table, you bless it, and you remember to eat last so you stay awake.",
        "Expect more invitations, warmer referrals, and small gifts finding you. Say yes selectively. Use a three-breath pause before accepting, then check two filters: does this feed your craft, and can you recover the energy by sleep, food, or quiet? Set a weekly intention budget with three priorities and two non-negotiable rests. Guard your body from sweet overindulgence: start mornings with water and protein, set a bedtime alarm, and walk 15 minutes after heavy meals. Consolidate gains: choose one flagship project and one experiment; close or delegate the rest. Track your plenty in a short log of inflows (praise, help, cash) and outflows (time, emotion), so generosity stays measured. Share 10% of windfalls with learning or community; keep 90% to stabilize you. When attention grows, update your boundaries script: clear office hours, a graceful no, and one monthly check-in with a trusted peer."
      ],
    },
    兄弟: {
      paragraphs: [
        "Lu, the open larder, flavors your Siblings palace with easy warmth and replenishment. You feel resources circulate between you and your brothers, sisters, and peer-kin like bowls passed around a table. Affection tastes tangible: a ride given, a bill picked up, introductions that open doors. You draw allies who want to nourish and be nourished; you, too, prefer to give before you ask. The inner weather is velvety and inviting, like steam rising from a shared pot, softening edges and making grudges melt. Under this sweetness, you attune to reciprocity and trust, and your voice naturally frames things as we rather than I. The shadow is over-sweetness: you may pad discomfort with favors, or confuse kindness with obligation. Yet the core archetype remains a cornucopia of kinship, inviting you to cultivate generosity that is structured, lucid, and genuinely mutual.",
        "You encounter offers, shared purchases, and group favors; siblings or close friends may invite you into ventures, travel, or co-living. Say yes when there is a clear ledger: write what is a gift, what is a loan, and the sunset date. Cap your generosity per month; keep a modest reserve you never pledge. Use a reciprocity check-in: every quarter, ask what feels balanced, what feels heavy, and adjust. Name roles before collaborating, and add an exit clause that requires a calm 48-hour pause before decisions. Risk zones include quietly covering others, triangulating through one sibling, and blurring money with approval. Remedies: split recurring costs by formula, use shared docs for expenses and promises, and keep one conversation per issue, not side chats. Nurture the sweetness through ritual meals, small thank-you notes, and honest noes; this sustains the flow without stickiness."
      ],
    },
    夫妻: {
      paragraphs: [
        "In the Spouse palace, Lu, the sweetening flow, turns partnership into a table where giving becomes bread and breath. You seek to nourish, to pour warmth into the space between you, to soothe edges with kindness and shared pleasures. The inner weather feels like honeyed light pooling on a wooden table, inviting hands to rest and open. You sense abundance in the relationship field and trust that generosity invites more life. This archetype softens you, widens your appetite for closeness, and primes you to celebrate ordinary moments. Yet it also tempts you to buy peace, to gloss over hard truths with treats, to equate value with what you provide. You may conflate affection with agreement, or mistake comfort for connection. The task is to let sweetness be honest, to feed the bond without numbing it.",
        "Playbook: expect invitations to co-create comfort—shared meals, joint purchases, perhaps merging plans or homes. Lean into hospitality and daily rituals, but set clear limits. Cap gift spending and agree on a generosity budget; use a simple envelope labeled comfort to hold discretionary funds. Schedule a weekly state-of-us with two parts: appreciations and one repair topic, then a small next step. Keep boundaries visible by practicing clean asks and clean noes. Track recurring patterns that money or favors try to paper over, and name them early. When conflict rises, pause for five slow breaths and touch a clay bowl for love notes; then return to specifics, not stories. Favor transparent calendars, rotating chores, and a shared wish list. Risk signals include guilt-giving, resentment, and silence after yes. Remedies: time-limited experiments, spending thresholds, a repair ritual, and a personal fuel practice that you keep even when romance runs hot."
      ],
    },
    子女: {
      paragraphs: [
        "You feel a mellow abundance moving through the Children palace. Lu, the gentle bestower, strengthens bonds between you and the young ones or the creations you call your children. Affection flows easier; praise tastes sweet on your tongue, and small victories multiply. You notice play becoming fertile ground for learning, and your patience has a warm, buttery heft, like a fresh loaf held in both hands. This current softens your stance without making you weak; you prefer to invite rather than push, to feed rather than force. Your creative offspring - drafts, prototypes, seedlings of ideas - respond to this gentleness by ripening. You glow when you witness growth, and you want to share the glow. The inner weather feels like early summer: enough rain to swell fruit, enough sun to coax laughter from the room.",
        "Expect more invitations related to children, teaching, or youth programs; your kids or students may receive gifts, scholarships, or glowing feedback. Fertility and creative conception trend upward, as do chances to monetize kid-centered projects. The risk is overindulgence: treats balloon into habits, schedules bloat, and boundaries blur. Set caps: a weekly gifting budget, clear screen-time windows, and a savings jar labeled for shared goals. Convert your warmth into structure: a standing one-on-one hour per child, a monthly showcase for their work, and a simple tracker for milestones, fees, and commitments. If co-parenting, document agreements and rotate generous gestures to prevent imbalance. Create an education cushion equal to three months of tuition or childcare; automate the transfers. Channel surplus joy outward: donate outgrown items, mentor once a month, plant a small herb pot together so gratitude has roots you can water."
      ],
    },
    财帛: {
      paragraphs: [
        "You stand where money warms instead of chills. In the Wealth palace, Lu, the sweetening current, coaxes resources toward you through rapport, small kindness, and well-timed offers. You sense price as a conversation rather than a wall, and you enjoy polishing value until it gleams. The inner weather is moist, fragrant, receptive: opportunities stick because you make others feel fed and seen. Picture warm bread on a wooden table, steam rising as you slice; that is how your proposals land. A sunlit bowl of coins invites an open palm, not a fist. You relish circulation over hoarding, and generosity becomes your magnet. Yet this same softness can blur edges; pleasure can nudge you past prudent limits. You thrive when you let wealth move like water, guided by channels you choose rather than by every shiny inlet.",
        "Momentum turns to results when you price for nourishment, not vanity. Set tiers that reflect effort, add a modest premium for slack, and bundle complementary offerings so clients feel held. Expect referrals, repeat orders, and surprise add-ons; welcome them with clear capacity limits and delivery dates. Guard against over-sweetening: cap discounts, avoid unpaid extras, and separate generosity from scope in writing. Build a three-month cash buffer; siphon 10% of every inflow into taxes and 5% into maintenance. Track weekly: invoices sent, days outstanding, average margin. Shorten payment cycles with deposits and milestone billing. Diversify streams so one faucet failure does not drain the basin. When desire urges a shiny purchase, wait 48 hours and compare lifetime yield to upkeep. Anchor spending to priorities you name each quarter. Keep receipts tidy, insure key tools, and schedule a monthly money date to steer the flow."
      ],
    },
    疾厄: {
      paragraphs: [
        "You stand inside a body that remembers feast after famine, as if rain finally reaches cracked soil. Lu, the warm replenisher, moves through your Health Palace like a ladle of broth poured into a deep bowl, inviting tissues to drink and store. Appetite stirs; sleep asks for softness; joints prefer oil to grit. This influence gathers sugar, warmth, and comfort into your cells, greening the edges of fatigue. You crave coziness, generous portions, and steady routines; your system absorbs blessings and keeps them, sometimes too well. The mood is mellow abundance, with plumped reserves and quick soothing. You feel repair quicken when nourished, and you sense how kindness multiplies quietly in the dark. The risk is simple: richness without circulation. You are learning to receive fully while keeping things moving, so sustenance becomes strength rather than residue.",
        "Play what nourishes without letting it congeal. Likely themes: easier recovery, regained appetite, mild weight drift, access to helpers who offer warm, hands-on care. Choose slow fuel over spikes: anchor meals with protein, fiber, and color; use a thumb of fat for satiety. Set richness guardrails: eat to 80% full, stop at the first comfortable sigh. Hydrate tactically: one tall glass on waking, one before each meeting. Train steadiness: two strength sessions and two brisk walks weekly, enough to keep the inner pot simmering. Track three signals on Sundays: waist fit, afternoon clarity (1-10), and bloat. Store a recovery cache: broths, electrolytes, ginger tea, heating pad, saline spray, Epsom salts. Schedule routine checkups and a seasonal lab review; note trends, not single numbers. When indulging, pair sweetness with movement. When flared, choose warmth, rest, simple soups, and early lights-out. Thank and redirect comfort into repair."
      ],
    },
    迁移: {
      paragraphs: [
        "In the Travel palace, you move outward with an easy magnetism. Lu, the open-handed host, loosens gates and invites provisions to meet you at the border. You read places quickly and they read you back; customs lines shorten, seats appear, and the right guide seems to stand where you need them. Your appetite for horizons wakes, not as escape, but as replenishment. You notice how small courtesies multiply into access: a shared snack, a precise hello, a generous tip. The air around departures feels friendly, like a warm tailwind at the platform; even your passport warms in your palm. This activation tunes your body to opportunity in motion, so you feel when to board, when to linger, and when to reroute. You are not forcing doors; they swing because your timing, tone, and offering align.",
        "Expect invitations to travel, remote clients, and lucky upgrades, along with strangers who open networks. Say yes selectively: choose trips that advance a clear aim, not just pleasant motion. Set a travel budget, hold deposits before booking, and price in per diems, currency fees, and buffer days. Create a departure checklist: visas, vaccinations, adapters, copies of IDs in cloud and a sealed envelope, local SIM, offline maps. Pack light and redundant: two cards, two charging cables, one sturdy lock whose click you feel. Guard your energy by blocking recovery windows and protecting sleep across time zones. Clarify boundaries with hosts and collaborators in writing. Risks include overbooking, lost items, and cultural missteps; offset with slower itineraries, a small emergency fund, and a basic phrase list. Mark thresholds with a simple grounding ritual: three slow breaths at each doorway, hand on the cool handle, then proceed."
      ],
    },
    交友: {
      paragraphs: [
        "Within the Friends palace, Lu, the open palm, warms the room of your social life. You draw in companions through ease rather than effort, and generosity becomes your native dialect. People feel fed around you; conversations thicken and sweeten, like honey stirred into tea. You notice how introductions, small gifts, and shared meals multiply, as if your network breathes in and out with you. This current invites you to host, to share tools and contacts, to circulate good will without keeping score. Yet its shadow is overfeeding: you can pour until your cup rims out. The inner weather is lush, humid, and fragrant; you move by instinct toward common tables and shared projects. Your role is not the loud leader but the hospitable center, arranging chairs so everyone can see each other.",
        "Expect a swell of invitations, referrals, and offers to co-host or co-create. Map your circle: list ten allies, note their strengths, and decide two mutual experiments for the next month. Set a generosity budget of hours, introductions, and small gifts; cap each category so you can sustain it. Use a 24-hour pause before saying yes, and require written scopes for collaborations. Vet new connections with a green/yellow/red checklist: green gives value first, yellow is vague, red pressures you for speed or secrets. Protect your energy with a monthly community night you control and a quarterly pruning of dormant groups. Track favors in a simple pencil ledger; checkmarks accumulate like seeds in a jar; schedule reciprocation dates. Do not co-sign debt; if needed, gift only what you can afford to never see again. When tensions rise, call a reset: name the ask, state your limit, propose one next step, and set a review date."
      ],
    },
    官禄: {
      paragraphs: [
        "In your vocation, the inner weather turns generous and steady. Lu, the Open Hand of increase, arrives at your desk like warm sunlight pooling on polished wood. You feel work feed you back as you feed it; efforts reach receptive soil, and results sprout with a soft, satisfying weight, like the heft of a well-made pen in your palm. In the 官禄 palace, this current wants to nourish reputation through consistent contribution and discreet goodwill. You attract support without begging for it; colleagues warm to your proposals, resources seem to show up right when needed, and deadlines meet you halfway. You still steer, yet the current carries. Your authority ripens not by force but by reliability, by the calm cadence of promises kept and the quiet scent of competence.",
        "Opportunities cluster: a stretch project lands, a decision seat opens, a sponsor offers cover. Say yes where value is visible and scope is containable. Price your time: cap commitments at a clear weekly capacity, and stage work in milestones that end with a two-sentence readout. Guard against the sweet risk of ease - overpromising, favoritism, or coasting. Map stakeholders by power and care; schedule brief check-ins, and document decisions in a simple log. Delegate with standards, not micromanagement: define outcomes, budgets, and stop rules, then grant room. Build buffers: one meeting-free block per day, one contingency day per month. Track wins in a living portfolio with numbers and anecdotes. Offer credit generously to strengthen your mandate. A small ritual helps: before you open email, touch the smooth rim of your mug and name the single result you will deliver today."
      ],
    },
    田宅: {
      paragraphs: [
        "You feel home as a living well, an ecosystem of generosity. Lu, the generous conduit, rises in your Property palace, softening edges and drawing resources to rooms and land. The inner weather is humid and fertile: you see how shelter becomes a vessel for nourishment and circulation. A warm pane of late-afternoon light rests on the wooden floor, and your ambitions take their shoes off. You are inclined to host, to plant, to stock the pantry, to upgrade what touches skin and sleep. You attract fair deals, helpful neighbors, and small windfalls tied to the ground you tend. Yet the impulse to accumulate comforts asks for discernment: abundance wants channels, not piles. Picture a bowl filling from a steady spring; you steward flow, arranging space so money, care, and people move through without clogging.",
        "Follow the urge to improve your dwelling, but price each change. Set a 10–15% contingency in renovation budgets; get two quotes and one reference check; verify permits. If you invest in property, favor well-kept units near stable transit; run cash flow with conservative vacancy and maintenance at 1–2% of property value yearly. Build a home reserve equal to three months of mortgage, utilities, and repairs. Treat moisture, wiring, and insulation before cosmetics. Aim for function you can feel: a door that closes cleanly, fresh paint still tacky to the touch. Host small gatherings to weave neighbor goodwill; it later opens parking, security, and local tips. Risk: over-furnishing, sentimental hoarding, or taking on a loan because it feels lucky. Remedy: a quarterly clear-out, a written buy list, and an exit rule set in advance (sell or rent if net yield drops below your floor). Install leak sensors, map shutoff valves, track energy use, and schedule seasonal checks so abundance stays flowing, not pooling."
      ],
    },
    福德: {
      paragraphs: [
        "In the 福德 palace, Hua Lu, the sweet spring of plenty, runs through your inner landscape. You feel resourced from within, as if a bowl of warm broth rests between your palms and will not run out. Quiet hours taste richer; solitude becomes a generous room rather than an empty hall. Gratitude rises without strain, and you forgive small flaws easily. Dreams carry soft guidance; you notice omens in simple things, like the steadiness of your breath when you walk. Your pace slows to humane, not lazy. You trust that unseen goodwill stands near and that giving starts with replenishment. This is not a trumpet but a hearth-fire, steady and scented with cedar. The mood is tender abundance: you keep more than enough attention to offer, without leaking yourself. Meaning feels edible, warm, and shared, not abstract or distant.",
        "Playbook: Resources and helpers arrive when you honor restoration. Expect invites to retreats, study circles, or quiet service; modest donations or anonymous aid boomerang as timely support. Schedule a daily rest ritual: 20 minutes of device-free stillness after lunch, candle lit, count 60 breaths. Keep a gratitude ledger and a dream log by the bed; note one useful symbol and one act of kindness each day. Set a generosity budget, 3-5% of income or two hours weekly, so giving stays steady, not draining. Risks: comfort spirals of scrolling, overeating, or rescuing everyone. Safeguards: fixed bedtime and sunrise walk, app limits, and a monthly solitude day. Seek meaning through service with boundaries; say, 'I can help for 45 minutes,' and stop. After heavy days, take a warm bath with salt and ask one trusted friend for perspective."
      ],
    },
    父母: {
      paragraphs: [
        "In the Parents Palace, Lu, the hearth of blessing, warms your dealings with parents, mentors, and the lineages behind you. You feel resources and affection flow more freely, as if a warm bowl placed in your hands invites you to eat and to share. You listen more readily to advice, and you speak with a soft brightness that eases old tension. Approval matters now, not as a chain but as a nourishing spice, and you notice how praise helps you grow. The inner weather is generous, domestic, and stabilizing; you prefer harmony over point-scoring, and you look for ways to repair frayed threads. Yet sweetness can blur edges: you may smooth too quickly, overlook boundaries, or give to be seen. Your task is to let kindness root without letting it run wild.",
        "Expect invitations to co-manage family resources, smoother talks with parents, and helpful introductions from elders or teachers. Gifts or financial support may emerge; you may feel moved to fund repairs, tuition, or healthcare. Use a clear allowance for giving, a written memo for any loan, and a shared checklist for eldercare. Schedule a weekly 20-minute call with an agenda: updates, needs, gratitude, decisions. Keep documents organized: insurance, medications, passwords, powers of attorney, and wills; store copies in a labeled envelope that fits your hand. Audit the home for safety: install a sturdy handrail. Prevent overextension by matching each yes with a boundary: amount, duration, outcome. Decline guilt-driven spending; offer time, rides, or meal deliveries instead. Track family transactions separately. If conflict flares, pause, breathe through the nose, name the goal, and return to facts before feelings."
      ],
    },
  },
  化权: {
    命宫: {
      paragraphs: [
        "You feel a firm current of command humming through your ribs, as if a bronze key warms in your palm and wants turning. In the Life Palace, this push concentrates your will, sharpens your yes and your no, and draws your posture taller. Quan, the lever, invites you to move from simple preference to decisive authorship. You notice where you once waited, you now initiate. Your tone becomes crisp, your stride lands with a dry-leaf crunch, and people look to you for cues. Clarity gathers; priorities line themselves in clean rows, and hesitation thins. You crave coherence, alignment, and the right to steer. Used cleanly, this is courage with a handle; used unconsciously, it becomes a grip that tightens on others and on yourself.",
        "Expect authority tests: colleagues ask you to chair meetings, family leans on your judgement, and projects wait for your green light. Take the helm, but design guardrails. Use a three-breath pause before big statements; write a one-page decision brief listing the aim, options, risks, and a sunset review date. Create a weekly personal council: two mentors or peers who challenge your reasoning. Build stamina with 90-minute focus blocks and a 10-minute walk to cool heat from the chest. Watch for overcontrol: micromanaging, interrupting, or carrying every load. Remedy with delegation using a Who-What-When checklist, and a rule of three choices you can live with. If conflict spikes, soften volume, slow tempo, and ask for one concrete request. Keep a power budget: track where you say yes, and reserve two daily slots for rest and reflection so leadership does not cannibalize your core."
      ],
    },
    兄弟: {
      paragraphs: [
        "Quan, the lever, turns on in the Siblings palace, and you feel a clear click toward leadership among equals. Your voice steadies and you prefer crisp lanes, shared standards, and the courage to say what others only hint at. The inner weather is a steady breeze over a lake, the tiller warm in your palm as the boat answers. This current frames you as steward rather than boss: you set tempo, negotiate space, and protect the weave of loyalty. You also notice impatience with dithering and a low tolerance for mixed signals. A second image: a knot pulling taut, not to choke, but to bind with care. Power, here, becomes the right to intervene when bonds fray, to push when momentum stalls, and to absorb heat so a brother, sister, or peer can cool. Authority is a service, tested in small, daily frictions.",
        "In practice, you get asked to coordinate plans, calm rifts, and decide who does what. Use this to build trust, not to win. Set roles early, write decisions in a shared note, and rotate facilitation on calls. Hold a 90-second check-in at the start: goals, concerns, next clear step. When conflict heats up, picture a cool glass in a hot room, and call a 24-hour pause before big messages. Risks include speaking over quieter siblings, fixing everything yourself, or corralling the group into your pace. Safeguards: ask before advising, name the choice set, and offer two good options plus a neutral exit. For joint expenses or errands, keep a simple ledger and payment deadline. Use a monthly sibling council, a two-minute round per person, and a standing question: what would feel fair to you right now?"
      ],
    },
    夫妻: {
      paragraphs: [
        "Quan, the lever of will, arrives in the Spouse Palace. You feel a clean urge to steer the course of partnership, to name direction, to claim responsibility, and to ask for reciprocal clarity. The inner weather runs bright and exacting: you favor crisp agreements, firm timelines, and a voice that does not tremble. Yet under that radiance lives a tender wish to be met as an equal, not as a commander. When fear flares, you may tighten your grip; when trust grows, you champion shared leadership. You hunger for vows that breathe, roles that adjust, and promises that actually hold. The body speaks through a warm metal ring around your finger and your hand on a steady tiller: you are ready to guide, but the boat moves best when both sets of hands feel the water together.",
        "Playbook: expect decision points about money, schedules, home moves, or parenting to cluster and ask for a clear lead. Use that drive to convene structure, not to bulldoze. Set a 30-minute weekly council with a simple agenda and a kitchen timer clicking on the table. Adopt a shared decision log in a notebook with crisp pages; date entries, note options, and mark agreements. Use the two-yes rule for major choices, and a 24-hour cooling period before unilateral actions. Map boundaries together: red (non-negotiables), yellow (conditions), green (easy yes). Rotate domains of leadership by week to balance effort. When tension spikes, call a reset word, pause screens, breathe for two minutes, and trade summaries before replies. Repair within 48 hours: name impact, state needs, and propose two workable next steps. If stalemates persist, bring in a neutral mediator early."
      ],
    },
    子女: {
      paragraphs: [
        "You sense your role with children sharpening into decisive leadership. Quan, the lever that concentrates will, moves through your Children palace like a steady hand on the tiller. You feel responsible to shape, protect, and direct, not out of control-fear but out of devotion. The inner weather is tensile: like a taut bowstring that must flex and not snap; like warm clay turning under your palms, responding to firm, patient pressure. You set standards, you ask for courage, you champion effort over outcome. When others hesitate, you step in, translate complexity into clear steps, and hold the line. Yet you also notice how command pulls at tenderness. Your power works best when it grants room for surprise, and when you listen before you decide.",
        "Events cluster around authority: a child seeks captaincy, contests a rule, or draws you into school politics. Use your influence like a whistle on the field, clear and brief, then let play resume. Set a family charter with 3 to 5 non-negotiables, posted where small hands can reach. Create choice within structure: two homework windows, a menu of chores, an autonomy budget for small purchases. Hold weekly one-on-ones; ask for their plan first, mirror it back, and add one stretch target. Track commitments on a visible board; celebrate completions with simple tokens. Risks include power contests, over-scheduling, and perfection spirals. Counter them with a pause ritual before directives, a red-pen rule that limits corrections, and repair steps after conflict: name impact, reset, and reconnect through a short shared task. If rivalry flares, assign rotating roles and shared goals. Keep evenings porous, like a lantern at dusk, so warmth can gather."
      ],
    },
    财帛: {
      paragraphs: [
        "You feel money matters condense around a core of intention; control, focus, and assertion hum in your hands. Quan, the lever that claims the helm, arrives in the Wealth palace, and you grip the throttle of cash with a steadier palm. You prefer clear terms, defined prices, and accountable flows; ambiguity irritates you and you clear it quickly. You notice where value leaks and where it can be concentrated. A cool, metallic calm accompanies you, like ink drying on a ledger; decisions set and numbers obey. This inner weather sharpens your appetite for authority over earning channels, costs, and reserves. You are not hoarding; you are directing. You test strength, raise thresholds, and shape exchanges so that effort equals payment. Under this archetype, you negotiate before you give, you plan before you spend, and you accept the weight of choice without flinching.",
        "On the ground, you gain chances to assert pricing, enforce terms, and re-route cash. You raise your rates or salary ask, tie offers to clear outcomes, and request deposits or retainers. You shorten payment windows to net-15, add late-fee clauses, and automate invoicing. You audit recurring costs, cut dead subscriptions, and renegotiate suppliers for volume or prepay discounts. Risks: you squeeze too hard and erode goodwill, you over-leverage with easy credit, or you chase status gear. Remedies: set a minimum viable rate and a walk-away line; use a tiered price ladder; hold a three-month cash buffer in a separate account, like a sealed canteen for dry days; route 1-5% to profit and 25-35% to taxes the moment income lands. Track a 13-week rolling cash forecast, run a weekly reconciliation, and keep dual-approval for transfers over a set amount. When emotions surge, pause 24 hours before any purchase above your threshold."
      ],
    },
    疾厄: {
      paragraphs: [
        "Quan, the lever that asserts, anchors in the realm of illness and recovery and compels you to take command of your body's thresholds. You feel authority rising with each heartbeat, a need to set terms with pain, fatigue, and recovery. The inner weather is brisk, purposeful, like a taut drum in your chest sending clear signals. Yet when control tightens too much, steam raps the lid of a kettle: symptoms push back, spike, or migrate. You are not at war with the body; you are the steward who allocates power, timing, and effort. You choose tempos for healing, appoint protocols, and insist on feedback. Discipline works, but rigidity cracks. When you listen for the precise edge between stimulus and strain, you notice where willpower helps and where it harms, and you learn to shift from command to consent without losing initiative.",
        "Playbook: during this activation, you likely meet turning points: decisive consults, medication adjustments, structured rehab, and clear lab trends. Your edge is focus. Choose one primary plan, name its checkpoints, and protect recovery windows. Use daily thresholds: pain 0-10, effort 0-10; stop at 6, reassess at 7. Track vitals each morning, log meds and side effects, and bring the log to appointments; let a clean clipboard and a lined grid carry part of your authority. Risks: overexertion, blood pressure spikes, inflammatory flares, injuries from haste, stimulant overuse, or abrupt withdrawal. Counter with interval pacing (work 25 minutes, rest 5), progressive loading at 5-10% weekly, and a steady sleep window. Eat an anti-inflammatory plate and hydrate to pale yellow. Set ergonomic timers, stretch, and breathe low and slow. Invite allies to help: pharmacist checks, a coach, a cool washcloth across the brow when urgency heats."
      ],
    },
    迁移: {
      paragraphs: [
        "You step across thresholds with a rising need to steer outcomes, not just follow signs. In the domain of travel and displacement, this force takes the shape of command: you read rooms quickly, set pace, and negotiate paths in unfamiliar places. Quan, the lever that tilts horizons, asks you to claim agency when borders blur. You prefer aisle seats, forward doors, first meetings. The air of transit sharpens your senses; a suitcase handle warms your palm as if it were a hilt. Your presence grows louder outside home ground, and people naturally defer when decisions must be made on the move. The inner weather is brisk and directional; you feel maps unfold under your voice. Authority is the current, but it needs a keel: purpose, courtesy, and situational awareness so that your drive guides rather than overwhelms the passage.",
        "Expect invitations to lead trips, handle relocations, or coordinate cross-border deals. Airports, stations, and visa counters put you at the front of the line, sometimes literally. Use the advantage by drafting itineraries, choosing routes with clear handoffs, and stating decision rights before departure. Build buffers: 90 minutes for transfers, two backup routes, and a 15% contingency in transport and lodging costs. Carry redundant power, offline maps, hard copies of IDs, and a brief local phrase list. Risks include overasserting with hosts, forcing timetables, or arguing with officials. Remedy with a calm cadence: breathe, ask open questions, and name shared outcomes. If moving house, pre-inspect leases, photograph utilities, and insure freight by declared value. Create a check-in rhythm with traveling partners at fixed landmarks. On arrival, ground yourself: touch the doorframe, drink water, note the nearest exit, and write three lines on what you intend to accomplish here."
      ],
    },
    交友: {
      paragraphs: [
        "Quan, the lever that concentrates influence, moves through your Friends palace. The inner weather grows dense and directive, like a current you can lean your weight against. You feel the impulse to organize, to braid scattered threads into a working cord, and others sense the torque in your voice. Circles you enter seek a center, and you become the momentary hinge. This is not loud dominance; it is the quiet pressure that aligns people toward a shared point. Picture a round table, the wood warm beneath your palms as chairs draw closer by inches. You carry a key quality now: the capacity to confer momentum and to withhold it. Used cleanly, it clarifies loyalties and purpose; used carelessly, it hardens cliques and makes friendship serve urgency.",
        "Expect invitations to coordinate projects, set agendas, or mediate among friends. You gain leverage through introductions and how you steer resources; use it to create shared wins, not quiet debts. Risks include overpromising, side conversations that split trust, and becoming the unofficial boss. Safeguards: set a clear scope for every favor; timebox asks; keep a simple ledger of commitments; rotate who chairs meetings; document decisions in a shared note within 24 hours. Ask for an explicit yes before speaking for a group. If tensions rise, separate social time from strategy spaces and install a cooling-off rule overnight. Put one visible board on the wall where sticky notes move from Ask to Done, so process stays public. Practice a 70/30 listening-to-speaking ratio when power is in your hands. Invite dissent early by asking for one risk per person. When a request breaches your boundaries, offer two alternative paths. Build bridges to adjacent circles to prevent cliques."
      ],
    },
    官禄: {
      paragraphs: [
        "Quan, the lever of mandate, lands in your Career palace like a hidden gear clicking into place. You feel the push to define terms, set tempo, and carry outcomes, as if a lacquered seal warms in your palm and asks to be pressed. This is not bluster; it is a current of responsibility that sharpens your voice and steadies your spine. You notice the architecture of roles and flows, and you instinctively reach for the hinge points that matter. Authority here is relational: you sense who lends legitimacy, who tests boundaries, and where silence signals consent. You crave clear scope, measurable ends, and visible standards. Ambition hums, but so does duty, inviting you to convert raw drive into structure, cadence, and accountable results.",
        "Career events likely cluster around authority. You get asked to lead a project, arbitrate trade-offs, or sign off on timelines, and a brass key seems to turn in every conversation. Use this moment to clarify mandate: request a one-page written scope, decision rights, budget ceiling, and success metrics. Build a delegation map with owners and due dates, then review it in a 15-minute weekly check-in. Set checkpoints by exception: define the minimum acceptable standard, then let people execute. Create a decision log, and share it with stakeholders every Friday. Risks include overreach, political frictions, and burnout. To counter them, schedule a 30-minute alignment with your manager each week, keep a two-step escalation path, and cap meetings to clusters. When conflict rises, ask each party for desired outcomes and non-negotiables, then restate agreements. End your day by closing the loop on three commitments and pausing before you lock the door."
      ],
    },
    田宅: {
      paragraphs: [
        "When power concentrates in the house and land, you feel an impulse to define edges, allocate rooms, and set the pace of the household. Quan, the lever that asserts form, arrives in the Property palace as a clear mandate. You stand in thresholds and decide what crosses. Your inner weather is organized, insistent, and protective; you treat space as a tool that should answer your will. Walls become statements, storage becomes strategy, and routines stack like bricks. The urge to fortify rises, not from fear, but from a wish to steward the hearth and ground. You hear the decisive click of a deadbolt and the soft thud of boxes settling, and you know you are claiming territory with intention and accountability.",
        "Events often cluster around renovations, purchases, leases, or a hard reset of household rules. You gain leverage to negotiate terms, set boundaries, and enforce standards. Use it cleanly. Price improvements with a phased scope, a 15% cash buffer, and a two-week slack in timelines. Pull permits, book inspections early, and photograph conditions before work begins. Order a title search and, if land lines are fuzzy, request a boundary survey. If renting, tighten clauses on maintenance and quiet hours, record an entry inventory, and time-stamp every handover as the ink dries on the lease. Create a house charter: roles, shared costs, guest policy, conflict repair steps, and a weekly check-in. Upgrade safety: test smoke detectors, label water shut-offs, map breakers, clear drainage, and service locks. Keep neighbor diplomacy warm but firm, and log agreements in writing. When power tilts, refuse brinkmanship; redirect it into checklists, blue tape, and transparent ledgers."
      ],
    },
    福德: {
      paragraphs: [
        "You feel an assertive current moving through your inner life; Quan, the lever, presses on the 福德 palace, where rest, meaning, and quiet luck abide. Sovereignty rises in your inner room, asking you to choose what you believe, how you restore, and which whispers deserve attention. Preferences sharpen, silence becomes deliberate, and faith feels less like drift and more like decision. The mind rallies like a small council, eager to issue orders. Yet the core impulse is to protect your peace, not to police it. When aligned, this activation makes conscience sturdy and calm, like a brass key turning in a quiet lock. It also washes stale narratives away, a cool stream rinsing dust from stones. You claim authorship of your mood and your myth, discovering that devotion can be measured in simple, repeatable acts.",
        "Playbook: you restructure your rest and meaning rituals. Likely events include pruning draining chats, setting solitude hours, and taking leadership in study, meditation, or service circles. Opportunities: reliable focus, mature hope, and tangible merit through small vows. Risks: zeal that hardens into control, insomnia from over-strict routines, spiritual one-upmanship, or guilt spirals. Safeguards: schedule a daily 20-minute quiet window, a weekly device sabbath, and a monthly half-day retreat. Set a bedtime alarm, cut caffeine after 2 p.m., and do six rounds of 4-7-8 breathing. Keep a three-line gratitude ledger; let ink dry before screens, like steam rising from a cup. Volunteer two hours monthly or give anonymously to balance authority with humility. Track mood triggers, and if rumination spikes, walk without audio. Share your boundaries with allies and review them every new moon."
      ],
    },
    父母: {
      paragraphs: [
        "In the Parents palace, your voice seeks to steer lineage and household customs. Quan, the lever of rightful influence, rises like a hand finding the helm in choppy water. You feel a crisp edge to your speech and a steadier spine when family rules, histories, and expectations surface. This inner weather mixes duty with independence: you want to honor what raised you while reshaping it so it fits the present. Authority is neither a throne nor a scold here; it is the quiet weight of a well balanced tool. You sense where to press and where to release, like smoothing a warm iron over a wrinkled sleeve, listening for the subtle hiss that says the fabric is yielding without burning.",
        "Expect assertive conversations with parents or elders about care, money, property, and boundaries. You may be asked to make choices or to take the lead; use agendas and timeboxes so talks do not sprawl. Translate love into logistics: compile a one-page contact sheet, medications list, and recurring appointments; keep scans of IDs, deeds, and directives in a shared folder. To reduce power struggles, ask before you advise, mirror their values, and offer two clear options instead of many. Involve siblings as allies with defined roles; rotate duties to prevent resentment. Choose a neutral table at a quiet cafe for difficult topics, and close each meeting with tea and three slow breaths to clear heat. If voices rise, pause, write the decision in plain language, and confirm by message. Watch tone and pacing; lower volume, slower tempo. Schedule respite for yourself, and set a weekly twenty-minute check-in that protects both privacy and care."
      ],
    },
  },
  化科: {
    命宫: {
      paragraphs: [
        "You stand at a careful threshold where intellect and character polish each other like river stones. Ke, the polisher of reputation, enters your Life Palace as a quiet artisan, sanding rough edges until grain shows. You crave clean lines in how you present yourself, and you favor exact wording. Curiosity sharpens; you ask better questions, and you enjoy translating complexity into clear shapes. Recognition matters, not as applause, but as proof that the form fits the essence. You prefer order, prefer to refine, prefer to be precise about your voice and posture. A small lantern in your chest steadying its flame becomes your compass; you pace yourself, measure twice, and cut once. Under this weather, you feel most alive when you synthesize learning into something useful, elegant, and unmistakably yours.",
        "Expect invitations to present, chances to earn credentials, and moments where your bio or face-to-face introduction carries weight. Use them. Build a one-sentence promise about who you are and a three-bullet proof of value; pin it above your desk. Set a weekly portfolio hour: curate examples, write captions, date each piece. Cap revisions at three passes; ship on the third. Seek one discerning mentor and two peer editors; schedule feedback before you start, not after. Risks: perfectionism, hiding behind study, chasing gold stamps. Safeguards: 90-minute focus blocks, then a walk; a mistake log with lessons; a public changelog for accountability. Practice a warm, grounded posture; rehearse your opening line until it lands like a smooth stone. When recognition arrives, redirect some light outward: teach a short workshop, credit collaborators, and document process. Identity grows cleanly when you pair rigor with service."
      ],
    },
    兄弟: {
      paragraphs: [
        "In the Brothers palace, you become the gentle judge and ready advocate of your circle. Ke, the polisher of names, refines your impulse to make things accurate, fair, and recognized. You notice how siblings and peers learn, where their edges soften, and how your words can become bridges. Under this weather, diplomacy feels natural; you speak with measured warmth, and people listen. You prefer evidence, consistent standards, and clean credit. Two simple images guide you: warm lamplight pooling on a round table, and fresh ink drying on a shared notebook. You gather companions, organize notes, and invite reason back into heated threads. You do not chase applause; you curate it so it lands where it belongs. In this season, belonging feels like a craft, and you practice it with care and steady hands.",
        "Playbook: expect invitations to co-author, moderate, or write recommendations for siblings and colleagues; expect skill-swaps and introductions that hinge on your judgment. Use structure to protect energy. Set a clear scope-of-help rule: cap hours, define deliverables, and write them in a shared document. Establish a credit protocol before work begins, and keep a simple ledger with neat columns for who did what and when. Timebox meetings with a small brass bell, and run two-minute round-robin check-ins to prevent dominance. Set referral terms in advance, including a percent or reciprocal rule. Watch for risks: invisible labor, overpromising on behalf of a brother, and reputational entanglement through gossip. Remedies: boundary phrases, a 48-hour tea call to repair friction, and a monthly peer showcase where each person presents one measurable result. Track promises weekly; praise precisely."
      ],
    },
    夫妻: {
      paragraphs: [
        "You stand in the Marriage Palace with Ke, the clarifier, brushing polish over how you relate. The inner weather is measured and lucid; curiosity softens edges; pride releases. You notice patterns, give names, and gently sand rough habits. You speak to understand, not to score. Praise lands like felt on wood, quieting echoes of old quarrels. You prefer order, shared language, and rituals that signal respect. Steam rising from a cup reminds you to slow attention and let it steep. Under this archetype, learning becomes affection: you swap books, compare maps of needs, draft better agreements. Your partner becomes a study companion rather than a rival, and the bond gains a clean grain, oiled by recognition and small, steady acknowledgments.",
        "Expect invitations to learn together: a class you both take, a couples workshop, or a project that needs clear roles. Opportunities arrive through praise or referrals; your partnership gets noticed for its civility. Risks: you drift into grading each other, polishing words while neglecting warmth, or chasing external approval. Safeguards: set a feedback boundary (ask, offer, then stop), keep a 3:1 ratio of appreciation to critique, and schedule a weekly 30-minute check-in with two timed rounds. Use a shared document for agreements; title decisions and date them. Create a repair ritual: a glass of water, two breaths, then each names one need and one action. Protect privacy; decline posting sensitive wins. Add touch to thought - hold hands while planning, or share hot tea so the cup's heat reminds you to soften. Aim for teachable, not perfect; celebrate small iterations."
      ],
    },
    子女: {
      paragraphs: [
        "You feel a clean, instructive breeze moving through the Children palace. Ke, the refining seal, polishes how you teach, guide, and receive signals from young ones and from your own fledgling creations. The mood is studious without heaviness; curiosity clicks open like a pencil case. You listen for evidence, trace patterns, and want to turn raw sparks into something named and shared. Two images: chalk dust rising from a neatly wiped slate; a small medal cool against a palm. Under this weather you prefer fairness, rubrics, and kind precision. You narrate steps, annotate drawings, and ask for reasons rather than obedience. Praise lands best when it names process. Your voice moves like a highlighter across the margin, revealing structure without stealing the page. You steward beginnings, certify progress, and keep the room calm enough for questions to grow.",
        "Playbook: Expect emails from teachers, invitations to contests, requests for feedback, or chances to publish a child's work. If you parent, mentor, or support kids, set a weekly review ritual under warm lamplight: skim notebooks, label wins, flag one skill to practice. Build a light portfolio: date-stamped snippets, photos, and two-sentence reflections. Guard against perfectionism and comparison by capping structured activities to two per term and scheduling ungraded play. If tempers rise around results, switch to effort metrics, timed breaks, and a walk that ends with cold oranges. Coordinate with schools using clear checklists, polite deadlines, and a single point of contact. If you have no children, apply the same method to prototypes or apprentices. Remedy for over-focus: one hour of silent co-reading, devices away. Remedy for shyness: small stages like a family reading night or a two-person science demo."
      ],
    },
    财帛: {
      paragraphs: [
        "You feel a steady, clarifying weather around your money life, as if columns align themselves when you look. Ke, the clarifier of value, enters your Wealth palace and invites you to make things understandable: what you charge, what you keep, what you reinvest, and what you bless to leave. Income arrives easiest when it is well explained and elegantly documented. Reputation and proof carry weight; a testimonial can act like interest, compounding trust. The mood is studious but not severe; you polish rather than chase. You translate effort into figures so others can agree with them. When you hold crisp ledger paper or watch a level beam scale, you feel the rightness of balance; excess wobble signals a story that needs editing. Your worth does not need noise, only structure, a clear frame through which value can be recognized.",
        "In practice, you attract clean earnings through clarity. Publish transparent pricing with a floor; set three tiers so clients self-select. Pair every quote with scope, success criteria, and change-order rules. Build a cash buffer of three to six months by reserving 10% of every inflow first. Track weekly: a 20-minute Friday review to reconcile accounts, tag expenses, and compare reality to plan. Showcase proof: case studies, credentials, and simple before/after numbers. Opportunities arise in teaching, writing, audits, or referral networks that reward thoughtfulness. The risks are polish that never ships, undercharging to be liked, and paperwork piling up. Guard yourself with timeboxes for research, a ready-to-send invoice template, and a price-rise calendar. If revenue bunches, smooth it with retainers and milestone billing. Keep a small bowl for receipts and a color-coded reserve ledger; simple rituals make your wealth sturdier."
      ],
    },
    疾厄: {
      paragraphs: [
        "Ke, the clarifying scribe, visits your Illness palace and turns scattered signals into legible notes. You stand inside your skin as if in a hushed library; shelves straighten, labels appear, and a soft desk lamp reveals what used to be dim corners. Sensations that once blur together separate into threads you can follow: which food warms, which pace steadies, which hour frays. This is not drama; it is discernment. You feel a gentle push to study your body, to respect tests, names, and patterns without becoming them. The energy favors refinement over force, clean edges over noise, like cool linen against a feverish forehead. You become curious rather than afraid, willing to ask precise questions, to learn the language of your metrics, and to practice care the way a scribe copies a manuscript, steady and attentive.",
        "In practice, you notice invitations to book checkups, request baseline labs, compare past results, and organize records. Use this surge to build a health brief: conditions, meds, allergies, emergency contacts, and a one-page timeline. Keep a daily symptom and energy log with a 1-10 scale, noting food, sleep, and stress. Set decision thresholds: if pain exceeds 6 for two days, call; if a new symptom persists 72 hours, seek evaluation. Risks include test chasing, catastrophizing, and skipping rest while researching. To counter them, cap research windows, ask for plain-language explanations, and bring a written question list. Practical supports help: morning light on your face, regular meals with protein and greens, posture breaks, handwashing, a HEPA filter if air is poor, and a simple med and supplement tracker so doses and interactions stay clear."
      ],
    },
    迁移: {
      paragraphs: [
        "You travel under a clear, studious sky when 迁移 lights up with Ke, the laurel of discernment. Movement does not scatter you; it sorts you. Stations, airports, and border lines become quiet halls of evaluation where you curate what matters and release what does not. Your curiosity takes form as checklists, questions, and annotated maps, and you derive esteem not from noise but from well-framed inquiry. The world feels like a library with moving shelves; each city presents a footnote, each stranger a reference. You notice standards, ethics, and methods in the cultures you cross, and you refine your own approach in response. The inner weather is cool and lucid, like the crisp air on a station platform and the smooth, fibrous drag of a boarding pass under your thumb; you proceed alert, polite, and exact.",
        "Your playbook favors structured journeys with learning value. Expect invitations to present, train, or mentor abroad, smoother visa steps, and serendipitous meetings with credentialed guides. Choose trips that deepen your craft; articulate a thesis for each itinerary. Cap cities to two; add 90-minute buffers to all transfers. Keep passport, visas, and tickets duplicated in cloud and wallet; carry a simple health kit. Prepare three questions and one generous introduction line; small, sincere gifts travel well. Budget roaming and transit data; preload maps; notify bank; set two-factor logins. Risks include overbooking, performative networking, and scattered notes. Remedy them by scheduling daily 20-minute synthesis, sending one thank-you per encounter, and arranging a quiet arrival day. Learn ten phrases, including help and directions. Keep an exit plan, emergency cash, and a trusted local contact. Teach what you learn within one week of return."
      ],
    },
    交友: {
      paragraphs: [
        "In the realm of friends and allies, Ke, the curator of discernment, tunes your social field to clarity. You gravitate toward companions who value learning, fair play, and careful speech. You listen as if weighing notes, then thread connections with a steady hand. Praise becomes precise, criticism becomes clean, and your circle feels like an ongoing seminar where everyone refines each other. The inner weather is crisp, cool, and lucid; drama thins, nuance thickens. You notice provenance: how a story was gathered, how a promise is kept. You prefer thoughtful pace over loud impact. Two images guide you: ink settling on vellum, and a brushed steel card case clicking shut. With them comes calm authority. You do not need to dominate a room; you catalog it, making space for the right minds to find each other and shine.",
        "Playbook: invitations to panels, study groups, and peer reviews arrive. Accept the ones that sharpen a current goal, not your vanity. Host small roundtables over a warm ceramic cup, and trade skills in 45 minute blocks. Keep a clean notebook margin for action items: one introduction you can make, one question to ask, one resource to share. Risks: gatekeeping, fussy tone, and gossip disguised as critique. Remedies: ask consent before giving feedback, name your role, and use a three step frame of observe, inquire, suggest. Cap your committees to two, your weekly social labor to two hours, and reply within 48 hours or decline kindly. Build a living roster with notes and review it monthly. When snobbery creeps in, introduce two unlikely people and learn from their bridge. If conflict sparks, schedule a repair walk, agree next steps in writing, and celebrate the smallest kept promise."
      ],
    },
    官禄: {
      paragraphs: [
        "In the Career palace, Ke, the clarifying seal, settles like cool light over a drafting table. You crave order, evidence, and earned respect; your mind sorts complexity into clean stacks, and your name carries the scent of proof. This activation tunes you to standards and recognition, not hollow applause but the kind that arrives after peer review and careful craft. You speak through well-made briefings and crisp deliverables, and doors open when your work reads like a reference. The inner weather is steady and precise: tick-marks, headings, citations, the rhythm of quality. A polished brass nameplate warms under your palm, yet you remember it belongs to the work, not the ego. In authority, you prefer legitimacy over force, delegating by method and rubric, and you draw allies who value clarity and fair process.",
        "Expect invitations to present, draft policy, audit workflows, or sit on review panels. Lean into them: codify processes, write a one-page standard for each recurring task, and teach it. Build a portfolio of proofs: case studies, metrics, and endorsements. Guard against perfection drift; set a 80/20 shipping threshold and a two-round review limit. Map stakeholders by influence and interest; brief executives with headlines, practitioners with checklists. Delegate by template and training, not by hope; run short clinics and assign stewards. Track authorship and sources to avoid jealousy; share credit publicly. Pace visibility with a monthly digest and a quarterly learning report. Keep approvals in one place, like color-coded tabs along a binder, so urgency does not smear the ink. When conflicts rise, default to transparent criteria, and invite a neutral peer to witness decisions."
      ],
    },
    田宅: {
      paragraphs: [
        "Inside the Home and Property palace, Ke, the curator of order, turns your dwelling into a living archive where meaning rests on shelves as much as in memory. You notice how rooms narrate values; you sort, label, and refine until the house speaks cleanly. Dust motes float in a wedge of afternoon light across well-scrubbed floorboards, and you feel the quiet authority of clarity. You favor plans, measured steps, and a standard for what belongs where. Ancestry and title records matter; you respect the paper trail and the craft of maintenance. Rather than extravagance, you seek rightness: proportions that breathe, storage that teaches, thresholds that pause the day. Ink dries crisp on labeled folders and deeds; your hands know where everything lives. The home becomes a school for attention, and your care confers a kind of gentle prestige.",
        "You advance property matters through study, documentation, and thoughtful timing. Expect inspections, appraisals, or permit reviews to hinge on completeness, not speed. Do your homework: build a digital archive, keep originals in a fireproof safe, and prepare a room-by-room checklist before contractors step in. Walk the block at dawn and late evening; note light, noise, and drainage. The measuring tape clicks; a pencil leaves calm tick marks along a stud, turning guesswork into lines. Opportunities favor energy audits, smart storage, and value added by careful finishes. Risks include perfectionism, delays for one more edit, and money siphoned into cosmetic tweaks. Set a budget with a 10% buffer, lock timeline gates, and pay contractors by milestones. Read covenants, verify boundaries, and invite neighbors into small decisions to earn goodwill. When tangled, seek expert letters; paper opens doors here."
      ],
    },
    福德: {
      paragraphs: [
        "You stand inside a clear inner library, shelves aligned, air smelling faintly of ink and cedar. Ke, the clarifying seal, presses gently on your thoughts, organizing memory and meaning into legible rows. You feel a quiet pride that does not shout; it hums, like a tuning fork aligning you to purpose. In the 福德 palace, this becomes the weather of merit and replenishment: you learn by resting well, and you rest by learning well. Insights come as soft, precise light, revealing patterns in your habits and beliefs. A silk bookmark slips between pages when you pause, reminding you that pauses are part of the text. The archetype here is the discerning student of the unseen, who cultivates grace by curating what enters the mind. You sort noise from nourishment, and the psyche breathes in clean, spacious air.",
        "You can expect thoughtful invitations to teach, join study circles, or curate resources for others. Recognition may arrive through kind notes, referrals, or a quiet seat at the table where values are set. Guard against polishing your inner world until it squeaks; perfectionism steals sleep and turns reflection into rumination. Build a nightly closing ritual: a warm bowl of tea, three lines in a gratitude ledger, devices off by 9, lights out by 10. Protect two weekly white-space blocks for unstructured rest or contemplative walks. Track mental loops: if a question repeats three times, park it in a single notebook and review on Fridays. Offer service that has edges: two hours of mentoring, one community class, or measured donation, then stop. Choose nutrient inputs: one book at a time, one course per quarter. If heaviness lingers, schedule counsel with a trusted elder or therapist."
      ],
    },
    父母: {
      paragraphs: [
        "In the Parents palace you move like lamplight pooling on a polished table, steady and clarifying. Ke, the seal of refinement, tunes you to civility, scholarship, and the quiet prestige that grows from doing things properly. You become a translator between generations: you turn rough recollections into clear notes, and tangled procedures into steps your elders can trust. The scent of ink on crisp forms and the soft thud of a closing folder soothe you because order means care. You honor lineage by gathering facts, dates, and testimonies, not to impress strangers but to keep the family name coherent. Your voice softens edges without hiding truths. You prefer counsel over command, mediation over debate, and you frame every request to your parents as an invitation to dignity. In this weather, reputation equals reliability, and learning becomes love in motion.",
        "On the ground, expect requests around documents, appointments, and reputation-sensitive decisions. You gather IDs, policies, reports, and contacts into a shared folder and a color-coded binder; you build a one-page summary for doctors, insurers, or housing officers. Likely openings: help a parent enroll in a class, write a concise bio for a community honor, record oral histories, or consolidate scattered records. Risks include overpromising, smoothing conflict to keep the peace, paperwork bottlenecks, and siblings pulling you into sides. Safeguards: set a weekly 20-minute agenda call; use checklists; require two confirmations before submitting forms; back up scans; date-stamp notes; and keep a list of translators, advocates, and attorneys for escalation. When emotions rise, name the issue in plain language, then propose three options with pros and cons. Cap your helper hours, rotate tasks, and schedule a quarterly audit. Celebrate progress with hot tea and a cleared desk."
      ],
    },
  },
  化忌: {
    命宫: {
      paragraphs: [
        "You host Ji, the solvent that reveals the grain, in the Palace of Self. Under its breath, veneers soften and peel; rooms you curated inside your name feel like wallpaper lifting at the corners. You sense drafts where you once felt seal. Your reflex is to grip labels tighter, but the season asks you to feel the raw wood. Doubt rises, not to drown you, but to rinse off glue. The mirror becomes a tide pool: distorted, then suddenly clear, showing barnacles as well as bright shells. Your voice catches, then returns leaner, true. Old loyalties tug; old poses itch. Shame cycles try to script you, yet something quieter hums under them, steady in your sternum. You learn to stand still, to name what is falling away without making it a verdict.",
        "In practice, identity matters get stirred. You may over-edit bios, dye your hair on impulse, quit roles too fast, or ghost a project when criticism stings like lemon on a cut. Use a 24-hour cooling rule before changes to your title, image, or commitments. Run small trials: a 30-day experiment instead of a forever shift. Keep an evidence log of wins and learnings; read it before hard talks. Schedule two weekly anchors that stabilize you, such as morning walks and a no-phone meal. Ask two mentors for mirrored feedback, then decide alone. Watch for self-sabotage tells: lateness, perfection loops, defensive jokes. Counter with minimum viable action today. Streamline your closet and digital profiles to three adjectives that feel alive now. Practice a clear no with one sentence and one alternative. Protect sleep, hydrate, and keep a simple breath count when panic buzzes."
      ],
    },
    兄弟: {
      paragraphs: [
        "You move inside a field of kinship where loyalties feel sticky and comparisons wake quickly. Ji, the knot that catches threads, settles in the Siblings palace like a frayed rope snagging on a nail. Old favors cling, small slights echo, and the air tastes like rain-soaked wool. You notice how a brother's sigh, a friend's late reply, or a teammate's half-promise can tug you into spirals of second-guessing. This activation heightens sensitivity to uneven exchanges and blurred boundaries; you read subtext, sometimes too well, sometimes not enough. Beneath it lives a yearning for clean ties: affection without scorekeeping, trust without fog. You want the table cleared and reset, plates warm and simple, everyone knowing their seat. The weather asks for patience, discernment, and the courage to loosen what no longer holds.",
        "Expect mixed signals, last-minute cancellations, and requests that come wrapped in obligation. A sibling may ask for money, a peer may want you to co-sign a plan, or a friend may triangulate you into their dispute. Your opportunity is to clarify containers. Before lending, set a written cap, repayment dates, and what happens if plans change; log transfers in a shared sheet and keep receipts. For shared projects, define roles, decision rights, and a two-signature rule for expenses. Institute a 'no same-day decisions' policy for heated asks, plus a 24-hour cool-down before replying to charged messages. Schedule brief check-ins with an agenda and a simple repair ritual: three appreciations, one clear request. Decline gossip; invite direct dialogue. Keep a small gift budget separate from loans. When tensions rise, step outside, touch a cold metal railing, breathe, and return to name the need rather than the blame."
      ],
    },
    夫妻: {
      paragraphs: [
        "Ji, the knot-maker, enters the spouse palace and tilts the inner weather toward stickiness and sensitivity. You notice how a small remark swells, as if ink smears across a letter you wanted to keep clean. Shadows of old loyalties and disappointments lean close; you reach for certainty, then recoil when it grips too tight. This activation tests the boundary between devotion and fusion, asking where you project, where you withdraw, and where you can breathe. The body tells the truth: jaw tight, chest shallow, heartbeat quick when intimacy demands clarity. Underneath, you want a simpler thread of connection, yet little snags multiply like a knot in silk that refuses to slide. The lesson is not punishment; it is precision: to see the story you add and the need you hide, then choose steadier contact.",
        "Expect signal-mixing in messages, old hurts resurfacing at anniversaries, and tug-of-war over time or spending. Create a clear playbook. Boundaries: adopt a 20-minute pause rule when voices rise; feet on the floor, cool water on wrists, return at a set time. Move delicate topics off text to a calm table with two chairs angled side by side. Run weekly 'state of us' check-ins: 30 minutes, three prompts: what felt good, what stung, what I need next week. Use a repair ritual after slips: name your part in one sentence, name the impact, propose a small redo within 48 hours. Track shared expenses and plans in a simple worksheet; agree thresholds for unscheduled buys. Guard against triangulation by keeping confidences and inviting witnesses only by joint consent. Celebrate small repairs; repetition rewires the bond."
      ],
    },
    子女: {
      paragraphs: [
        "In the Children palace, your heart moves like a violin string tuned a touch too tight: sensitive, singing, and quick to squeal when pressed. Ji, the knot that guards the gate, asks you to feel the snag where love and fear meet. You notice small missteps magnified—an ignored text, a stubborn mood, a missed recital—and the mind writes harsh headlines. You crave to protect, then doubt the way you protect. Tension hums in the room, and you rehearse futures to keep risk at bay. You sense the child in front of you, or the projects you parent, as a kite pulling at its line, testing whether the thread will hold. Under this weather, you become a careful listener, learning to hear what is not said, and you practice holding steady so the string can sing without snapping.",
        "Practically, expect schedule snags, mercurial moods, and crossed wires with kids, students, or creative offspring. Build buffers: add 15 minutes around handoffs and keep a clear backup plan. Use kind scripts for tense moments: name the feeling, offer one choice, breathe together for ten counts. Track basics on one page—sleep, meals, screens, medications, homework—and review weekly to spot patterns, not culprits. Create a small repair ritual: a warm drink, eye contact, a simple apology. For schooling, choose fewer activities with deeper attention; budget for one tutor or tool that removes friction. If fertility or health matters arise, seek second opinions and keep a dated log of tests and treatments. Strengthen co-parent and mentor agreements in writing; clarify who decides, who drives, and who de-escalates. For your steadiness, set a quiet corner with a soft object and a timer; step there before you speak when heat spikes. Celebrate one shared joy daily."
      ],
    },
    财帛: {
      paragraphs: [
        "With Wealth, Ji, the knot in the purse-string, sharpens your senses around what leaks and what lures. You notice how scarcity stories fog the glass, how shame hums whenever numbers come close. A tarnished coin that sticks to your palm becomes the emblem: you hold tight, yet it smears and clings, reminding you that attachment can cost as much as loss. Expenses feel like a slow drip from a loosened faucet, more irritant than flood, but constant enough to shape mood and choices. You question prices, distrust windfalls, and second-guess generosity. Yet beneath the fret, a sober instinct wakes: you crave clean boundaries, true costs, and honest exchanges. This activation asks you to separate need from noise, to name each outflow, and to let money be a tool rather than a test of worth.",
        "Expect sticky costs: forgotten subscriptions, processing fees, clients who pay late, and offers you price too low. Turn this into training. Build a zippered pouch around your income: route every payment into one account, then auto-move fixed amounts to taxes, savings, and operations. Set a price floor using your real hourly load and materials; publish terms with deposits, late fees, and stop-work triggers. Keep a 10-20% buffer on quotes. Reconcile each week for 30 minutes; tag outflows by purpose; cancel duplicates. Use category caps and two no-spend days to reset impulse. Clear high-interest balances first, then seed a three-month fixed-cost reserve. For sales, create three tiers, anchor with the middle, and review margins quarterly. If cash flow wobbles, pause variable ads, negotiate vendor timelines, and offer pay-in-full incentives. Chalk lines on a workshop floor keep each dollar to its lane."
      ],
    },
    疾厄: {
      paragraphs: [
        "You stand in the body's weather station, feeling pressure shift behind the ribs and in the jaw hinge. Ji, the snag in the weave, appears here as a sensitive barometer: small stresses pull, unresolved toxins thicken, and symptoms tend to cluster like burrs on cloth. This activation does not doom you; it heightens feedback. It asks you to notice the grain of your energy and the places where you push past warning lights. In the Sickbed palace, it paints the edges of sensation in bolder ink, so you register aches faster and recover best when you respect pace. Think of a damp cellar that clears when the door cracks open and air moves; attention and steady ritual are that draft. Your task is to become a careful caretaker of thresholds, neither bracing against the tide nor drifting, but steering with felt intelligence.",
        "Expect periods where old injuries echo, digestive or skin flare-ups, and fatigue after social overexertion. The opportunity is precise body literacy: track sleep, pain, and foods in a simple log; rate daily load 1-10 and cap at 7. Book baseline labs and one specialist you trust; assemble a care folder with meds, allergies, and insurance. Build safeguards: morning light within 30 minutes of waking, a fixed sleep window, protein and water early, a 20-minute walk, calf and chest stretches, and a 4-6-8 breathing set when symptoms spike. Reduce frictions: preportion safe snacks, program refill reminders, and keep a small kit in your bag. Name red flags (new chest pain, sudden weakness, black stool) and decide exactly whom you contact. Decline energy-drainers without apology. Schedule quarterly reviews to adjust plans. You do not chase crises; you build margins, then move within them."
      ],
    },
    迁移: {
      paragraphs: [
        "You step beyond your door and the air tilts slightly. Ji, the snag in the seam, arrives in the Travel palace to sensitize you to friction and misfit. It does not curse your road; it tunes your nerves so you can feel where agreements, timetables, and borders do not quite line up. You travel lighter by choice, attentive to subtext in signs and the mood of thresholds. A grain of sand under your insole teaches you to pause and adjust before blisters form. A map smudged with rain reminds you that routes are living things, not commandments. You move with alert humility, scanning for detours, collecting small clues, revising expectations. You discover that safety and luck expand when you accept course corrections quickly and honor the quiet yes that lives under noisy plans.",
        "Your playbook is simple, layered, and calm. Expect last-minute schedule shifts, visa questions, rerouted commutes, unfamiliar checkpoints, or relocations that require two passes. The upside is craft: you design resilient itineraries, carry less, and choose truer alliances on the road. Risks cluster around rush, lost papers, vague directions, overpaying, and fatigue. Safeguards: book refundable routes; pad every connection with a 15% time and cash buffer; keep a document triad- originals, paper copies, and encrypted cloud; color-code packing into modules; carry a dry bag and a charged power bank; pin clinics, embassies, and safe lodgings on offline maps. Rehearse a Plan B route before you need it. Learn five local phrases. Set two daily anchors- morning check-in and evening debrief. Tell a trusted buddy your itinerary and check-in times. For moves, label boxes by first-night needs and test the new commute at the same hour."
      ],
    },
    交友: {
      paragraphs: [
        "Among friends and networks, Ji, the burr in the handshake, makes you feel the grain of connection. You notice how invitations carry fine print and how warmth sometimes hides a ledger. The inner weather is prickle and pull: you want closeness, yet your skin registers snags. A joke lands crooked, a favor returns with a hook, a group chat tilts into pressure. Like ink swirling in water, motives diffuse and blur before they settle. This activation does not doom your friendships; it trains your fingertips. You sense the moment a boundary thins, the second a story asks you to pick a side, the quiet charge behind a compliment. Rather than withdraw, you stand present and tactile, willing to test texture, name friction, and sand rough edges into honest, breathable contact.",
        "Your playbook: slow the gate. Use the rule of three touches before trust - one unstructured chat, one small task together, one boundary conversation. Track red flags: rushed urgency, shifting stories, mocking what you share, casual breaches of others' privacy. Keep money clean: do not lend to friends; if you choose to, set a cap, document terms, and assume it is a gift. For collaborations, write a one-page brief with roles, deadlines, and exit conditions; share it in the thread so it is visible. Limit sprawling group chats; move decisions to short calls with notes. When gossip surfaces, reflect feelings and redirect to source. Schedule monthly one-to-one check-ins with your core allies; practice clear asks and timely no's. After gatherings, take a 10-minute debrief to list wins, snags, and any repairs. Keep an exit ritual: a thanks, a boundary, and a clean stop without back-channeling."
      ],
    },
    官禄: {
      paragraphs: [
        "You stand in the career hall where pressure concentrates and choices echo. Ji, the knot that reveals weak seams, tightens around your deadlines and titles until you notice what does not hold. You see frayed handoffs, vague authority, and shortcuts that no longer pass quietly. The inner weather shifts between static and clarity, like a buzzing light in the corridor that finally steadies. Under this activation you feel compelled to correct, to strip varnish, to face the smudge on the report you wanted to ignore. It is not punishment; it is the grit that polishes craft. You learn which responsibilities truly belong to you, and which you carry only from habit. In that recognition, your posture firms; you claim sober pace over haste, and you choose clean lines over noise, ready to mend what must be mended.",
        "Expect clogged approvals, shifting scopes, and critiques that arrive with red pen heat. Use them. Map stakeholders and name a single owner for each decision. Write decision logs, assumptions, and next steps in a shared page; send a one page weekly brief with risks, asks, and dates. Build buffer time and require a midcourse review before final delivery. Delegate with checklists and small milestones; measure outcomes, not busyness. When authority blurs, ask for written remit and escalation paths. Practice hard conversations: say no to hidden work, yes to clear tradeoffs. Run premortems and a final red team check on critical releases. Keep version control tight, archive threads, and track change requests. Restore your center with brief, grounded rituals: breathe by the window, roll your shoulders, feel the mug warm your palms. You steer by clarity, and the knot slowly loosens."
      ],
    },
    田宅: {
      paragraphs: [
        "Ji, the knot that tightens, enters your Property palace as a slow, insistent pressure. It feels like a door that swells in humid weather and resists your hand, or a hairline crack that keeps catching your eye. You notice how unresolved titles, shared spaces, and inherited expectations gather weight, pressing you to choose what truly belongs. The house becomes a truthful instrument, sounding off wherever you postpone care. You are invited to witness the cost of attachment and the relief of release. Boundaries sharpen: owner versus occupant, heirloom versus clutter, sanctuary versus storage. The mood narrows but clarifies; you locate the line between stewardship and burden. This activation does not scold; it calibrates. When you listen without dramatizing, you sense a plainer strength emerging, built from fewer possessions, cleaner agreements, and a steadier rhythm of maintenance that answers the place you inhabit.",
        "Expect delays with deeds, mortgage conditions, strata or HOA rules, neighbor boundaries, or repairs that reveal hidden rot. Preempt with due diligence: moisture and foundation checks, roof and drainage inspections, updated survey, thorough title search. Keep communications in writing; photograph conditions on handover and store timestamps. Build buffers: a housing reserve of 3-6 months, and 10-15% extra for any renovation. For buying, insist on inspection and financing contingencies, cap offers, and walk the block at night to sample noise. For renting, read repair and exit clauses, document defects within 48 hours, and use certified notices if needed. For letting property, screen consistently, hold deposits in escrow, and schedule seasonal maintenance. Inside, declutter by rule, not mood: donate a box per week until surfaces breathe. Install water sensors, label shutoffs, and map breakers. Each dusk, light one room and choose one fix you can complete within 48 hours."
      ],
    },
    福德: {
      paragraphs: [
        "In the 福德 palace, your inner climate tilts toward vigilance and self-questioning, as if meaning must be earned before you can rest. Ji, the knot that tightens around joy, asks you to notice where comfort slips through your fingers and where guilt tries to take its place. Thoughts loop, promises to yourself feel fragile, and silence can hum with static. Yet this pressure reveals what truly soothes you when appearances fade. You learn to track micro-movements of mood and to meet them without flinching. Picture a moth tapping a lampshade, insistent yet harmless; picture cold tea with sugar that will not dissolve, patience needed to stir longer. You are refining stamina of spirit: the capacity to stay present when the sweetness arrives late. Your sanctuary becomes earned, not by sacrifice, but by honest attention.",
        "On the ground, expect mood dips after overstimulation, over-giving, or long stretches without true rest. Build a daily ritual that cannot be negotiated: a slow dusk walk without your phone, or ten minutes of steady nasal breathing with a longer exhale. Track energy in a simple 1-5 log and plan gentler tasks on low days. Set a compassion budget so you do not rescue to avoid your own feelings. When worry spirals, write it for three minutes, then close the notebook and touch a smooth stone in your pocket. Protect sleep with a consistent lights-out and lighter dinners; reduce late caffeine. Choose one act of meaning each week, modest and real, like delivering a warm bowl of soup. Seek counsel early, not in crisis. Celebrate small restoration, and let boundaries hold so grace can accumulate."
      ],
    },
    父母: {
      paragraphs: [
        "You move through the Parents palace under Ji, the knot-puller. Conversations snag on tiny barbs, and old expectations feel sticky on your skin. You want warmth and approval, yet you brace for the flinch. The inner weather is fog over familiar streets: you know the route, but visibility narrows. A frayed phone cord in your hand reminds you how connection both carries and cuts. Cold tea on a kitchen table waits like a question you have not answered. You sense patterns of sacrifice, guilt, and blame asking to be composted. This activation invites you to witness what does not get said, to name it gently, and to let some inherited scripts end with you. Tenderness becomes strategy; boundaries become breath; your steadiness turns into a quiet bell that calls the room back from old storms.",
        "On the ground, expect uneven timing, mixed messages, and duties that arrive suddenly. Parents may revisit old grievances, misplace documents, or face health reviews. You defuse volatility by slowing the tempo. After each call, write a three-line summary and share it. Ask one precise question at a time. Set a 20-minute limit for hot topics, then pause. Put medications, contacts, and passwords in a clear folder that snaps shut. Create a caregiving budget, name roles with siblings, and agree on a decision tree for emergencies. Use a simple ritual before visits: rinse your hands, touch your heart, and choose one intention. Risks include resentment, overspending, and triangulation. Remedies: neutral meeting spaces, a calm third party, and micro-rests; sip a modest bowl of warm soup before hard talks. Keep key paperwork ready: ID scans, powers of attorney, and a list of next steps."
      ],
    },
  },
}