/**
 * Coordinate mapping for "Navigate Your Year Like a Pro" PDF template
 * Generated by AI analysis of reference images
 * 
 * Note: PDF coordinates start from bottom-left corner
 * - x: horizontal position from left
 * - y: vertical position from bottom
 * - Page dimensions: 384 x 600 points (custom size, not standard A4)
 */

export interface FieldPosition {
  x: number;
  y: number;
  fontSize: number;
  fontFamily: "Helvetica" | "Helvetica-Bold" | "Helvetica-Oblique";
  color: { r: number; g: number; b: number };
  maxWidth?: number;
  align?: "left" | "center" | "right";
}

export interface PageFields {
  [key: string]: FieldPosition;
}

/**
 * Page 7 - Monthly Overview (JANUARY 2026 example)
 */
export const page7Fields: PageFields = {
  // Main month header (large white text on red background)
  // Note: PDF coordinates start from BOTTOM-LEFT, page height is 600
  month: {
    x: 53,
    y: 550, // ~50 points from top (600 - 50 = 550)
    fontSize: 48,
    fontFamily: "Helvetica-Bold",
    color: { r: 1, g: 1, b: 1 }, // White
    maxWidth: 300,
    align: "left",
  },
  
  // Career score (right side number)
  careerScore: {
    x: 430,
    y: 510,
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    align: "right",
  },
  
  // Wealth score
  wealthScore: {
    x: 430,
    y: 470,
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    align: "right",
  },
  
  // Relationship score
  relationshipScore: {
    x: 430,
    y: 430,
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    align: "right",
  },
  
  // Health score
  healthScore: {
    x: 430,
    y: 390,
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    align: "right",
  },
  
  // Current season text (e.g., "Spring")
  currentSeason: {
    x: 75,
    y: 290,
    fontSize: 24,
    fontFamily: "Helvetica-Bold",
    color: { r: 1, g: 1, b: 1 }, // White on red background
    maxWidth: 150,
  },
  
  // Core palace name (e.g., "Career Palace")
  corePalaceName: {
    x: 290,
    y: 280,
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    maxWidth: 200,
  },
  
  // Season description paragraph
  seasonDescription: {
    x: 75,
    y: 250,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: { r: 1, g: 1, b: 1 }, // White
    maxWidth: 150,
  },
  
  // Palace description paragraph
  palaceDescription: {
    x: 290,
    y: 220,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: { r: 0.2, g: 0.2, b: 0.2 },
    maxWidth: 200,
  },
};

/**
 * Template configuration
 */
export const navigateYourYearTemplate = {
  pages: {
    7: page7Fields,
    // Add more pages as needed
  },
  
  // Page dimensions
  pageSize: {
    width: 384,
    height: 600,
  },
  
  // Background colors for covering old text
  backgrounds: {
    redHeader: { r: 0.7, g: 0.1, b: 0.1 },
    beige: { r: 0.98, g: 0.95, b: 0.9 },
    white: { r: 1, g: 1, b: 1 },
    darkRed: { r: 0.6, g: 0.1, b: 0.1 },
  },
};

export default navigateYourYearTemplate;
